### ISSUE TITLE
Slider is not properly reset on redraw

### ISSUE THREAD

**Issue by sbaechler** [fulup-bzh/RangeSlider#5]
When I set the slider to 100%, then change to another page and return to the page that has the slider on it, then the handle is way off the scale.

The transform-x CSS value gets added to the value that the component already has, but it should not in this case.

Update:
I managed to reproduce the error on initial load as well if the value is set to 100%.

The reason for this is not a reset issue but a timing problem. When the `setValue` method is called wich calculates the offset, the template variables are not resolved yet. Therefore the layout is not correct because the full name of the variables is displayed.

Once they are resolved the elements become smaller and the handle is therefore off the element.

I wonder if it is possible to delay the calculation of the offset until angular has finished the digest loop?

This is how it looks with the debugger:
![unbenannt](https://cloud.githubusercontent.com/assets/288516/15823702/26034d88-2bfc-11e6-9580-a57da4d1ee09.PNG)

**Comment by fulup-bzh** [comment]
I have no answer about how to handle this in Angular. If you have a proposal please send a patch I will be more than happy to integrate it.

**Comment by sbaechler** [comment]
Done :)

**Comment by fulup-bzh** [comment]
Wonderfull
