### ISSUE TITLE
New bower release

### ISSUE THREAD

**Issue by rthunbo** [fulup-bzh/RangeSlider#8]
Hi.

Could you make a new bower release.

Best regards,
Rolf Thunbo

**Comment by fulup-bzh** [comment]
I updated GitHub this should be enough for Bower, isn"t it ?

**Comment by rthunbo** [comment]
I believe you need to do a Github release. Right now I get the following when forcing install of 0.0.3:

bower bzm-range-slider#^0.0.3       not-cached https://github.com/fulup-bzh/RangeSlider.git#^0.0.3
bower bzm-range-slider#^0.0.3          resolve https://github.com/fulup-bzh/RangeSlider.git#^0.0.3
bower bzm-range-slider#^0.0.3     ENORESTARGET No tag found that was able to satisfy ^0.0.3

Additional error details:
Available versions in https://github.com/fulup-bzh/RangeSlider.git: 0.0.1

**Comment by fulup-bzh** [comment]
Done, does it fix the issue ?

**Comment by rthunbo** [comment]
Yes, thank you.
